### ISSUE TITLE
旧developerWorksのコンテンツで移行されていないものがある

### ISSUE THREAD

**Issue by nishi2go** [IBM/developer_jp#2]
旧developerWorksで以下の記事の他のシリーズがpart 6, 7, 10が無いようです。記事の内容は現在でも有用だと思いますので、復元できないか検討いただけないでしょうか。

https://www.ibm.com/developerworks/jp/ysl/library/tivoli/y-tiv-basicmaximo8/index.html

また、カテゴリもMaximo関連であればIoTが適切かと思います。

よろしくお願いします。

**Comment by taijihagino** [comment]
お世話になります。IBM Developer JP ウェブサイトの管理チームです。
旧dWで掲載していたコンテンツはGlobalのものを翻訳したものとローカルで個別に作成したものがありました。
新サイトへの移行の際に、Globalの判断で全てのコンテンツを移行することはできないのでアクセス数などを基に多くのコンテンツが移行対象外（つまり削除）となりました。これは、各記事単体で評価されシリーズ物を括る形では判断されておりません。今回ご指摘いただきましたシリーズの一部が欠けているのはこういった経緯からと推察いたします。
なお、残念ながら現在では復元元の公式のデータはもうありません。但し、以前dW Japan編集長であったメンバーがローカルで残していたアーカイブに当該コンテンツが含まれていれば復元可能な可能性はありますので確認させて頂きます。
誠に申し訳ございませんが、ご理解賜りたくお願い申し上げます。

**Comment by yamachan** [comment]
@nishi2go さん、 @taijihagino さん、こんばんは！

何故か呼ばれた気がしたので…

それぞれ以前にダウンロードしたファイルがありましたので、PDF 版を以下に置きました。
とりいそぎこちら参照いただければとおもいます。

http://rinco.jp/tmp/y-tiv-basicmaximo6-pdf.pdf
http://rinco.jp/tmp/y-tiv-basicmaximo7-pdf.pdf
http://rinco.jp/tmp/y-tiv-maximo_cluster-pdf.pdf

**Comment by taijihagino** [comment]
@yamachan さん、ありがとうございます！
こちら、編集チームへ連携させていただきます。
